baseURL = 'https://frecklemaid.github.io/'
languageCode = 'en-us'
title = 'Specual'
theme = "archie"
copyright = "© Frecklemaid"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
	mode="toggle"
	useCDN=false
	customcss=["css/newdark.css", "css/newlight.css"]
	subtitle = "Minimal and Clean [blog theme for Hugo](https://github.com/athul/archie)"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

