baseURL = "https://specual.me/"
languageCode = "en-us"
title = "Specual"
theme = "archie"
copyright = "© Frecklemaid"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

"disqusShortname"="specual"

paginate=5

[params]
	mode="toggle"
	useCDN=false
	subtitle = "Speculative and nonfiction book reviews."

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/frecklemaid"

[[params.social]]
name="Goodreads"
icon="book"
url="https://www.goodreads.com/user/show/33340133-mackenzie"

[[params.social]]
name="Storygraph"
icon="book-open"
url="https://app.thestorygraph.com/profile/mfletcher"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

